### ISSUE TITLE
Synology NAS Docker Kurulum Rehberi Eklenmesi

### ISSUE THREAD

**Issue by rifatozkancomtr** [Amm1rr/WebAI-to-API#42]
# Synology NAS Docker Kurulum Rehberi Eklenmesi

## Açıklama
Mevcut Docker.md dosyası genel Docker kurulumu için hazırlanmış ancak Synology NAS kullanıcıları için özel bir rehbere ihtiyaç var. Synology NAS'ta Container Manager kullanımı, GUI ve SSH yöntemleri ile detaylı kurulum adımları eklenmelidir.

### 1. Docker.md dosyasına Synology bölümü eklenmesi:

**Eklenecek içerik:**
- Synology Container Manager kurulumu
- GUI ve SSH yöntemleri
- Port konfigürasyonu
- Reverse proxy kurulumu
- Troubleshooting bölümü
- Otomatik güncelleme (Watchtower)

### 2. Synology'ye özel docker-compose.yml örnekleri:

**synology-docker-compose.yml** dosyası oluşturulması:
```yaml
services:
  web_ai:
    image: cornatul/webai.ai:latest
    container_name: web_ai_server
    restart: unless-stopped
    ports:
      - "6969:6969"
    environment:
      - PYTHONPATH=/app/src
      - ENVIRONMENT=production
    volumes:
      - ./config:/app/config
      - ./logs:/app/logs
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=3600
```

### 3. Synology.md ayrı dosyası oluşturulması:

Detaylı Synology kurulum rehberi için ayrı bir markdown dosyası oluşturulabilir.

## Hedef Kullanıcılar
- Synology NAS sahipleri
- Docker konusunda yeni olan kullanıcılar
- GUI tercih eden kullanıcılar
- Türkçe dokümantasyon arayan kullanıcılar

## Fayda
- Daha geniş kullanıcı kitlesine ulaşım
- Synology platformunda kolay kurulum
- Troubleshooting kolaylığı
- Community desteği artışı

## Teknik Detaylar

**Eklenmesi gereken bölümler:**
1. **Synology Önkoşullar**
   - DSM versiyonu
   - Container Manager kurulumu
   - SSH aktivasyonu

2. **GUI Kurulum Yöntemi**
   - Container Manager kullanımı
   - Registry'den image çekme
   - Container konfigürasyonu

3. **SSH Kurulum Yöntemi**
   - Docker Compose kullanımı
   - Komut satırı örnekleri

4. **Ağ ve Güvenlik**
   - Port konfigürasyonu
   - Firewall ayarları
   - Reverse proxy kurulumu

5. **Bakım ve Güncelleme**
   - Otomatik güncelleme
   - Backup stratejileri
   - Log yönetimi

Bu rehber hem yeni başlayanlar hem de ileri düzey kullanıcılar için yararlı olacaktır.
